"""Add fund_type to FundHistory and update summary logic

Revision ID: 1eefc8554fb8
Revises: 9b3bceadda58
Create Date: 2025-06-06 01:45:04.936195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eefc8554fb8'
down_revision = '9b3bceadda58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_type', sa.String(length=50), nullable=False, comment="Type of fund or 'ALL_TYPES_MONTHLY_SUMMARY' for overall total"))
        batch_op.create_index(batch_op.f('ix_fund_history_fund_type'), ['fund_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_history_fund_type'))
        batch_op.drop_column('fund_type')

    # ### end Alembic commands ###
