"""Add last_updated to CompanySetting

Revision ID: 3fc652a10ae0
Revises: c14b1150134a
Create Date: 2025-05-04 00:11:32.809844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func # Import func for server_default

# revision identifiers, used by Alembic.
revision = '3fc652a10ae0'
down_revision = 'c14b1150134a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True, server_default=func.now())) # Add as nullable first with server default

    # Update existing rows - Set last_updated to current time for existing rows
    op.execute('UPDATE company_setting SET last_updated = CURRENT_TIMESTAMP WHERE last_updated IS NULL')

    # Now make the column non-nullable
    with op.batch_alter_table('company_setting', schema=None) as batch_op:
        batch_op.alter_column('last_updated', nullable=False, server_default=None) # Make non-nullable, remove server_default if managed by model

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_setting', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
