"""Remove redundant total_sales and total_payout from FundHistory

Revision ID: 41b7abfa0c4f
Revises: 1eefc8554fb8
Create Date: 2025-06-06 01:49:27.839812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b7abfa0c4f'
down_revision = '1eefc8554fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_history', schema=None) as batch_op:
        batch_op.drop_column('total_payout')
        batch_op.drop_column('total_sales')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sales', sa.NUMERIC(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_payout', sa.NUMERIC(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###
