"""Add fund_type to Fund model

Revision ID: 61364b643e71
Revises: b8df7a8900af
Create Date: 2025-05-08 00:50:46.875939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61364b643e71'
down_revision = 'b8df7a8900af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.alter_column('fund_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_funds_fund_type'), ['fund_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funds_fund_type'))
        batch_op.alter_column('fund_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
