"""Add FundMonthlySummary table

Revision ID: 8366f954b344
Revises: 2725b2025432
Create Date: 2025-06-06 01:04:14.570743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8366f954b344'
down_revision = '2725b2025432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_monthly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='The last day of the month this summary represents'),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calculated_net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_monthly_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_monthly_summaries_snapshot_date'), ['snapshot_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_monthly_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_monthly_summaries_snapshot_date'))

    op.drop_table('fund_monthly_summaries')
    # ### end Alembic commands ###
