"""empty message

Revision ID: 8b418c981c01
Revises: 
Create Date: 2025-05-15 04:12:18.737198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b418c981c01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_referral_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('signup_referral_code_used', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_personal_referral_code'), ['personal_referral_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_personal_referral_code'))
        batch_op.drop_column('signup_referral_code_used')
        batch_op.drop_column('personal_referral_code')

    # ### end Alembic commands ###
