"""Rename FundMonthlySummary to FundHistory

Revision ID: 9b3bceadda58
Revises: 8366f954b344
Create Date: 2025-06-06 01:30:59.043094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3bceadda58'
down_revision = '8366f954b344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='The last day of the month this summary represents'),
    sa.Column('sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_history_snapshot_date'), ['snapshot_date'], unique=False)

    with op.batch_alter_table('fund_monthly_summaries', schema=None) as batch_op:
        batch_op.drop_index('ix_fund_monthly_summaries_snapshot_date')

    op.drop_table('fund_monthly_summaries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_monthly_summaries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_date', sa.DATE(), nullable=False),
    sa.Column('total_sales', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('total_payout', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('calculated_net_profit', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_monthly_summaries', schema=None) as batch_op:
        batch_op.create_index('ix_fund_monthly_summaries_snapshot_date', ['snapshot_date'], unique=False)

    with op.batch_alter_table('fund_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_history_snapshot_date'))

    op.drop_table('fund_history')
    # ### end Alembic commands ###
