"""Add fund_type to Fund model

Revision ID: b8df7a8900af
Revises: c63b1e3dc87b
Create Date: 2025-05-08 00:34:49.983285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8df7a8900af'
down_revision = 'c63b1e3dc87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.drop_column('fund_type')

    # ### end Alembic commands ###
