"""Add preferred_nav to User model

Revision ID: c14b1150134a
Revises: 
Create Date: 2025-05-03 19:48:26.908774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14b1150134a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_nav', sa.String(length=10), nullable=False, server_default='sidebar'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_nav')

    # ### end Alembic commands ###
