"""Update Sale model for simplified structure and remove Configuration model.

Revision ID: c63b1e3dc87b
Revises: 
Create Date: 2025-05-07 22:42:34.353583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63b1e3dc87b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('member_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.create_index(batch_op.f('ix_sales_leader_id'), ['leader_id'], unique=False)
        batch_op.create_unique_constraint('uq_leader_sales', ['leader_id', 'created_at'])
        batch_op.create_foreign_key(None, 'users', ['leader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_leader_sales', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sales_leader_id'))
        batch_op.drop_column('total')
        batch_op.drop_column('member_count')
        batch_op.drop_column('leader_id')

    # ### end Alembic commands ###
